"""Generate the bundle's pyproject.toml and manifest.json from the repo's own metadata.

Anything that must agree with the published package — name, version, licence, URLs, the
Python floor, the dependency ceilings — is read from the repo's `pyproject.toml`, so the
bundle cannot drift from what it packages. Only the copy aimed at the person installing
the bundle is literal here; that is deliberately different text from the PyPI summary,
which is written for developers.
"""

import asyncio
import json
import os
import pathlib
import sys
import tempfile
import tomllib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]

DISPLAY_NAME = "Delta Exchange"
PUBLISHER = "Delta Exchange"
KEYWORDS = ["trading", "crypto", "options", "futures", "market-data"]


SHORT_DESCRIPTION = "Live market data and your Delta Exchange India account."

LONG_DESCRIPTION = (
    "Ask about Delta Exchange India in plain English: live prices, option chains, "
    "order books, funding and open-interest history, plus your own positions, orders, "
    "fills and balances.\n\n"
    "**Read-only unless you change Mode.** Left at `read`, this cannot place, change or "
    "cancel orders, and can never move funds. Set Mode to `trade` and it can place, edit "
    "and cancel real orders on the environment you selected — there is no size limit, and "
    "orders are sized in contracts rather than coins. Every mutation is written to an "
    "audit log under `~/.delta-exchange-mcp/audit/`. Leave this at `read` unless you "
    "specifically want an assistant trading your account.\n\n"
    "**Both credential fields or neither.** A key without its matching secret is ignored "
    "and you get market data only — the two are always used together. Trading additionally "
    "needs a key with trading permission, not just Read Data.\n\n"
    "**Market data needs no setup** — leave the API key and secret empty and everything "
    "except your own account still works.\n\n"
    "**To see your account**, create a key at delta.exchange under Account → API Keys with "
    "the **Read Data** permission. Both halves are shown only once, at creation. Paste them "
    "into Configure. Your key is stored by this app and is sent only to Delta's API, from "
    "your own machine.\n\n"
    "**Environment** must be `india_prod` for the real exchange, or `india_testnet` for the "
    "practice site at demo.delta.exchange. A key only works against the site it was made on."
)

# Claude Desktop renders each description twice: as help text under the label AND as the
# input placeholder, where anything past ~60 characters is truncated mid-word. Keep these
# short enough to read cleanly in both roles; the detail lives in LONG_DESCRIPTION.
USER_CONFIG = {
    "api_key": {
        "type": "string",
        "title": "API key",
        "description": "Optional — leave empty for market data only.",
        "sensitive": True,
        "required": False,
    },
    "api_secret": {
        "type": "string",
        "title": "API secret",
        "description": "Required if you filled in the key above.",
        "sensitive": True,
        "required": False,
    },
    "environment": {
        "type": "string",
        "title": "Environment",
        "description": "india_prod (real) or india_testnet (practice).",
        "default": "india_prod",
        "required": True,
    },
    # There is no enum type in user_config — only string, number, boolean, directory and
    # file — so this is a string the user edits, exactly like environment above. It
    # defaults to read: arming order placement has to be a thing someone chose to type.
    "mode": {
        "type": "string",
        "title": "Mode",
        "description": "read (default), or trade to allow placing orders.",
        "default": "read",
        "required": True,
    },
}


def project() -> dict:
    """The repo's own [project] table — the single source of truth for shared metadata."""
    with (REPO / "pyproject.toml").open("rb") as f:
        return tomllib.load(f)["project"]


def wheel_name(proj: dict) -> str:
    return f"{proj['name'].replace('-', '_')}-{proj['version']}-py3-none-any.whl"


def render_pyproject(proj: dict) -> str:
    """The bundle's own project file, pinned to the vendored wheel.

    The dependency ceilings are copied from the repo rather than restated. mcp 2.0 removed
    `mcp.server.fastmcp`, so a bundle that resolved above the repo's ceiling would die at
    import — and one that pinned below a raised ceiling would too.
    """
    deps = [f"{proj['name']}=={proj['version']}", *proj["dependencies"]]
    rendered = ",\n".join(f'    "{d}"' for d in deps)
    return (
        "# Generated by make_bundle.py — edit that, not this.\n"
        "[project]\n"
        f'name = "{proj["name"]}-bundle"\n'
        f'version = "{proj["version"]}"\n'
        f'requires-python = "{proj["requires-python"]}"\n'
        f"dependencies = [\n{rendered},\n]\n"
        "\n[tool.uv.sources]\n"
        f'{proj["name"]} = {{ path = "wheels/{wheel_name(proj)}" }}\n'
    )


async def tool_entries() -> list[dict[str, str]]:
    """Introspect the server to list every tool the bundle can register.

    The environment is forced rather than defaulted so the manifest depends only on the
    source being packaged, never on the shell the build ran in — real exported credentials
    would otherwise be read at build time for no reason.

    Trade mode is forced because the declared list has to be the *superset*. `tools_generated`
    is false, which promises the runtime never exposes anything beyond this list, and a user
    who sets Mode to trade reaches all of it. Listing only the read surface would break that
    promise the moment someone opted in.
    """
    os.environ["DELTA_MCP_MODE"] = "trade"
    os.environ["DELTA_API_KEY"] = "placeholder"
    os.environ["DELTA_API_SECRET"] = "placeholder"
    # The shared settings file is redirected as well, or the build reads the developer's
    # own. Measured: a DELTA_MCP_DEBUG=1 line in ~/.delta-exchange-mcp/config.env writes
    # get_debug_status into the manifest — 42 tools instead of 41 — and CI, which has no
    # such file, then rejects that manifest as stale. It also stops a build creating a file
    # in a home directory it has no business touching.
    os.environ["DELTA_MCP_CONFIG_FILE"] = str(pathlib.Path(tempfile.mkdtemp()) / "config.env")
    from delta_exchange_mcp.server import build_server

    tools = await build_server().list_tools()
    return [
        {
            "name": t.name,
            "description": (t.description or "").strip().splitlines()[0].strip(),
        }
        for t in sorted(tools, key=lambda t: t.name)
    ]


def render_manifest(proj: dict, tools: list[dict[str, str]]) -> dict:
    urls = proj.get("urls", {})
    return {
        "manifest_version": "0.4",
        "name": proj["name"],
        "display_name": DISPLAY_NAME,
        "version": proj["version"],
        "description": SHORT_DESCRIPTION,
        "long_description": LONG_DESCRIPTION,
        "author": {"name": PUBLISHER, "url": urls["Homepage"]},
        "repository": {"type": "git", "url": urls["Repository"]},
        "homepage": urls["Homepage"],
        "documentation": urls["Documentation"],
        "support": urls["Issues"],
        "icon": "icon.png",
        "license": proj["license"],
        "keywords": KEYWORDS,
        "server": {
            "type": "uv",
            "entry_point": "server/main.py",
            "mcp_config": {
                "command": "uv",
                "args": [
                    "run",
                    "--directory",
                    "${__dirname}",
                    "--frozen",
                    "python",
                    "server/main.py",
                ],
                "env": {
                    # Declared, not omitted. The host substitutes this from the form, whose
                    # default is read, so an ambient DELTA_MCP_MODE=trade in the environment
                    # the app was launched with cannot arm trading behind the user's back.
                    "DELTA_MCP_MODE": "${user_config.mode}",
                    "DELTA_MCP_ENV": "${user_config.environment}",
                    "DELTA_API_KEY": "${user_config.api_key}",
                    "DELTA_API_SECRET": "${user_config.api_secret}",
                },
            },
        },
        "tools": tools,
        "tools_generated": False,
        "user_config": USER_CONFIG,
        "compatibility": {
            "claude_desktop": ">=0.10.0",
            "platforms": ["darwin", "win32", "linux"],
            "runtimes": {"python": proj["requires-python"]},
        },
    }


def main() -> None:
    what = sys.argv[1]
    proj = project()

    if what == "version":
        print(proj["version"])
    elif what == "wheel-name":
        print(wheel_name(proj))
    elif what == "pyproject":
        (HERE / "pyproject.toml").write_text(render_pyproject(proj))
        print(f"wrote pyproject.toml (deps from {REPO.name}/pyproject.toml)")
    elif what == "manifest":
        tools = asyncio.run(tool_entries())
        out = HERE / "manifest.json"
        out.write_text(json.dumps(render_manifest(proj, tools), indent=2) + "\n")
        print(f"wrote manifest.json ({len(tools)} tools, version {proj['version']})")
    else:
        raise SystemExit(f"unknown target: {what}")


if __name__ == "__main__":
    main()
